/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title ADC single channel conversion
 * \abstract The Versatile Analog-to-Digital Converter (VADC) is configured to measure an analog signal using background scan request.
 * \description An analog input channel is continuously converted using the background scan mode.
 *              The input value is determined by the potentiometer on the board.
 *              Two LEDs are used to indicate a voltage interval.
 *              Thus depending on the conversion value, one or both LEDs are on.
 *
 * \name ADC_Single_Channel_1_KIT_TC275_LK
 * \version V1.0.0
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \keywords ADC, ADC_Single_Channel_1, VADC, conversion, single channel scan
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_ADC_Single_Channel_1_KIT_TC275_LK-TR-v01_00_00-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC27D_iLLD_UM_1_0_1_12_0.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ADC_Single_Channel.h"
#include "ASCLIN_UART.h"
#include "GTM_TOM_PWM.h"
#include "Bsp.h"
#include "IfxVADC_Adc.h"
#include "IfxDSADC.h"
#include "DSADC.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define WAIT_TIME   100             /* Number of milliseconds to wait between each conversion                       */

IfxCpu_syncEvent g_cpuSyncEvent = 0;
unsigned int RESULTReg = 0u;

#define ADC_RESOLUTION 4096   // 12-bit -> 2^12 = 4096 steps
#define VREF_MV 3300          // Max voltage reference in millivolts (5000mV = 5.0V)

/*********************************************************************************************************************/
/*-------------------------------------------- Utility Functions ----------------------------------------------------*/
/*********************************************************************************************************************/

/* Convert ADC raw value to millivolts */
unsigned int adcToMilliVolt(unsigned int adcValue) {
    if (adcValue >= ADC_RESOLUTION) {
        adcValue = ADC_RESOLUTION - 1;  // clamp to max
    }
    return (adcValue * VREF_MV) / (ADC_RESOLUTION - 1);
}

void UARTgetPeriodDuty(void)
{
    // Update duty if changed
      static float lastDuty = -1.0f;
      if (g_uartDutyCycle != lastDuty) {
          lastDuty = g_uartDutyCycle;

          //send_UART("Duty: %.0f%%\n\r", g_uartDutyCycle * 100.0f);

          setDutyCycle(PWM1,g_uartDutyCycle*100.0f);
          setDutyCycle(PWM2,g_uartDutyCycle*100.0f);

      }

      // Update frequency if changed
      static uint32 lastFreq = 0;
      if (g_uartFrequency != lastFreq) {

          if(g_uartFrequency<3000)
          {
               //send_UART("Set Freq :>= 3000 Hz\n\r");
          }
          else
          if(g_uartFrequency>30000)
          {
              //send_UART("Set Freq :<= 30000 Hz\n\r");
          }
          else
          {
              //send_UART("Freq: %u Hz\n\r", g_uartFrequency);
          }

          setFreq(PWM1,g_uartFrequency);
          setFreq(PWM2,g_uartFrequency);
          lastFreq = g_uartFrequency;
      }
  }


/*********************************************************************************************************************/
/*-------------------------------------------------Main--------------------------------------------------------------*/
/*********************************************************************************************************************/
int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!! */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /* Initialize a time variable */
    Ifx_TickTime ticksFor100ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    init_ASCLIN_UART();                 /* Initialize UART */
    IfxCpu_enableInterrupts();          /* Enable interrupts after initialization */
    send_ASCLIN_UART_message();         /* Initial hello string from Infineon example */

    /* Initialize GTM TOM module */
     initGtmTomPwm();

    /* Initialize LEDs */
    initializeLEDs();

    /* Initialize VADC */
    vadcBackgroundScanInit();

    /* Start the background scan */
    vadcBackgroundScanRun();

    /* Initialize the DSADC module      */
    init_DSADC();

    while(1)
    {

        UARTgetPeriodDuty();

        // Sweep duty
        g_uartDutyCycle += 0.005f;

        if (g_uartDutyCycle > 1.0f) g_uartDutyCycle = 0.005f;
        setDutyCycle(PWM1,g_uartDutyCycle*100.0f);

        //send_receive_ASCLIN_UART_message();
        /* Update LEDs depending on the measured value */
        RESULTReg = indicateConversionValue();

        /* Convert ADC bits to mV */
        unsigned int mv = adcToMilliVolt(RESULTReg);

        /* Send formatted results via UART */
        // Print the raw ADC register value (in bits, 0–4095 for 12-bit ADC)
        send_UART("Input PWM Freq :  %u Khz ", g_uartFrequency/1000);

        send_UART("DutyCycle : %u ", (uint16)(g_uartDutyCycle*100));

        send_UART("VADCBits: %u ", RESULTReg);

        // Print the converted voltage in millivolts (integer value, 0–5000 mV)
        send_UART("VADCmVolt: %u mV ", mv);

        float32 dsAdcbits = (float32)Get_DSADCbits(); /* Run the conversion continuously and send the bits  */

        float32 dsmv      = (float32)Get_DSADCVoltage();      /* Run the conversion continuously and send the Volts  */

        /* Send formatted results via UART */
        // Print the raw ADC register value (in bits, 0–4095 for 12-bit ADC)
        //send_UART("DSADCBits: %.2f ", dsAdcbits);

        // Print the converted voltage in millivolts (integer value, 0–5000 mV)
        send_UART("DSADCmVolt: %.2f mV \n\r ", dsmv*1000);

        wait(ticksFor100ms);
    }
    return (1);
}
