/**********************************************************************************************************************
 * \file GTM_TOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_TOM_PWM.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm_Tom.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_TOM    20                                      /* Interrupt priority number                    */
#define LED                 IfxGtm_TOM1_4_TOUT14_P00_5_OUT          /* LED which will be driven by the PWM          */
#define PWM_PERIOD          50000                                   /* PWM period for the TOM                       */
#define FADE_STEP           PWM_PERIOD / 100                        /* PWM duty cycle for the TOM                   */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

#define LED1  IfxGtm_TOM1_4_TOUT14_P00_5_OUT   // P00.5 → TOM1_CH6
#define LED2  IfxGtm_TOM1_5_TOUT15_P00_6_OUT    // P00.6 → TOM0_CH1

// Global driver/config structs
IfxGtm_Tom_Pwm_Config g_tomConfig[2];
IfxGtm_Tom_Pwm_Driver g_tomDriver[2];

uint32 g_fadeValue = 0;                                             /* Fade value, starting from 0                  */
sint8 g_fadeDir = 1;                                                /* Fade direction variable                      */

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

void ConfigGtm(uint8 tmpIdx, const IfxGtm_Tom_ToutMap *Tmp, uint32 TempFreq, uint8 TempDuty);
void setPwm(uint8 tmpIdx, const IfxGtm_Tom_ToutMap *pin, uint32 freqHz, float dutyPercent);
/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the TOM */
void initGtmTomPwm(void)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock                         */

    // --- LED1: P00.5 ---
    //ConfigGtm(PWM1,&LED1,50000,0);
    setPwm(PWM1, &LED1, 20000, 50.0);   // 20 kHz, 50% duty
    setPwm(PWM2, &LED2, 20000, 50.0);   // 20 kHz, 50% duty

    /* Initialize the configuration structure with default parameters */

}

void setPwm(uint8 tmpIdx, const IfxGtm_Tom_ToutMap *pin, uint32 freqHz, float dutyPercent)
{
    uint32 fxclk = (uint32)IfxGtm_Cmu_getFxClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Fxclk_0, TRUE);

    // Protect against invalid duty %
    if (dutyPercent < 0.0f) dutyPercent = 0.0f;
    if (dutyPercent > 100.0f) dutyPercent = 100.0f;

    // Compute period and duty
    uint32 period = (fxclk / freqHz) - 1;
    uint32 duty   = (uint32)((dutyPercent / 100.0f) * (period + 1));

    // Init config
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig[tmpIdx], &MODULE_GTM);
    g_tomConfig[tmpIdx].tom        = pin->tom;
    g_tomConfig[tmpIdx].tomChannel = pin->channel;
    g_tomConfig[tmpIdx].period     = period;
    g_tomConfig[tmpIdx].dutyCycle  = duty;
    g_tomConfig[tmpIdx].synchronousUpdateEnabled = TRUE;
    g_tomConfig[tmpIdx].pin.outputPin = pin;

    IfxGtm_Tom_Pwm_init(&g_tomDriver[tmpIdx], &g_tomConfig[tmpIdx]);
    IfxGtm_Tom_Pwm_start(&g_tomDriver[tmpIdx], TRUE);
}


void ConfigGtm(uint8 tmpIdx, const IfxGtm_Tom_ToutMap *Tmp, uint32 TempFreq, uint8 TempDuty)
{
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig[tmpIdx], &MODULE_GTM);

    g_tomConfig[tmpIdx].tom        = Tmp->tom;
    g_tomConfig[tmpIdx].tomChannel = Tmp->channel;
    g_tomConfig[tmpIdx].period     = TempFreq;
    g_tomConfig[tmpIdx].dutyCycle  = TempDuty;
    g_tomConfig[tmpIdx].synchronousUpdateEnabled = TRUE;
    g_tomConfig[tmpIdx].pin.outputPin = Tmp;   // pass pointer to the constant

    IfxGtm_Tom_Pwm_init(&g_tomDriver[tmpIdx], &g_tomConfig[tmpIdx]);
    IfxGtm_Tom_Pwm_start(&g_tomDriver[tmpIdx], TRUE);
}


/* This function creates the fade effect for the LED */
void fadeLED(void)
{
    if((g_fadeValue + FADE_STEP) >= PWM_PERIOD)
    {
        g_fadeDir = -1;                                             /* Set the direction of the fade                */
    }
    else if((g_fadeValue - FADE_STEP) <= 0)
    {
        g_fadeDir = 1;                                              /* Set the direction of the fade                */
    }
    g_fadeValue += g_fadeDir * FADE_STEP;                           /* Calculation of the new duty cycle            */
    //setDutyCycle(uint8 tmpIdx , uint32 dutyCycle);                  /* Set the duty cycle of the PWM                */
}


/* This function sets the duty cycle of the PWM */
void setDutyCycle(uint8 tmpIdx , uint32 dutyCycle)
{
    if (dutyCycle < 0.0f) dutyCycle = 0.0f;
    if (dutyCycle > 100.0f) dutyCycle = 100.0f;

    g_tomConfig[tmpIdx].dutyCycle = (uint32)((dutyCycle * (float)g_tomConfig[tmpIdx].period) / 100.0f);     /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_tomDriver[tmpIdx], &g_tomConfig[tmpIdx]);                                        /* Re-initialize the PWM                        */
}

void setFreq(uint8 tmpIdx, uint32 Freq)
{
    uint32 fxclk = (uint32)IfxGtm_Cmu_getFxClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Fxclk_0, TRUE);

    // Compute period and duty
    uint32 period = (fxclk / Freq) - 1;

    g_tomConfig[tmpIdx].period = period;                                                                      /* Set the timer period                         */
    IfxGtm_Tom_Pwm_init(&g_tomDriver[tmpIdx], &g_tomConfig[tmpIdx]);                                        /* Re-initialize the PWM                        */
}

void setFreqDutyCycle(uint8 tmpIdx, uint32 Freq,uint32 dutyCycle)
{
    g_tomConfig[tmpIdx].period = Freq;                                                                      /* Set the timer period                         */

    if (dutyCycle < 0.0f) dutyCycle = 0.0f;
    if (dutyCycle > 100.0f) dutyCycle = 100.0f;

    g_tomConfig[tmpIdx].dutyCycle = (uint32)((dutyCycle * (float)g_tomConfig[tmpIdx].period) / 100.0f);     /* Change the value of the duty cycle           */

    IfxGtm_Tom_Pwm_init(&g_tomDriver[tmpIdx], &g_tomConfig[tmpIdx]);                                        /* Re-initialize the PWM                        */
}

void setDutyCycle1(uint32 dutyCycle)
{
    g_fadeValue = dutyCycle * g_tomConfig[0].period /100;
    g_tomConfig[0].dutyCycle = g_fadeValue;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_tomDriver[0], &g_tomConfig[0]);                /* Re-initialize the PWM                        */
}

